
package com.geo.server.wits;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WITSMLPortType", targetNamespace = "http://example.com/witsml")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WITSMLPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.geo.server.wits.GetWellAndWellboreResponse
     */
    @WebMethod(operationName = "GetWellAndWellbore", action = "http://example.com/witsml/GetWellAndWellbore")
    @WebResult(name = "GetWellAndWellboreResponse", targetNamespace = "http://example.com/witsml", partName = "parameters")
    public GetWellAndWellboreResponse getWellAndWellbore(
        @WebParam(name = "GetWellAndWellboreRequest", targetNamespace = "http://example.com/witsml", partName = "parameters")
        GetWellAndWellboreRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.geo.server.wits.GetCapabilitiesResponse
     */
    @WebMethod(operationName = "GetCapabilities", action = "http://example.com/witsml/GetCapabilities")
    @WebResult(name = "GetCapabilitiesResponse", targetNamespace = "http://example.com/witsml", partName = "parameters")
    public GetCapabilitiesResponse getCapabilities(
        @WebParam(name = "GetCapabilitiesRequest", targetNamespace = "http://example.com/witsml", partName = "parameters")
        String parameters);

}
